apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: zr6nr69jv-nodejs 
  janus-idp.io/tekton: zr6nr69jv-nodejs
  backstage.io/kubernetes-id: zr6nr69jv-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zr6nr69jv-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml