apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zr6nr69jv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zr6nr69jv-nodejs 
  name: zr6nr69jv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zr6nr69jv-nodejs 
